export const nationalityToIsoCode: Record<string, string> = {
  // Top & European
  "Albania": "al",
  "Algeria": "dz",
  "Angola": "ao",
  "Argentina": "ar",
  "Armenia": "am",
  "Australia": "au",
  "Austria": "at",
  "Belgium": "be",
  "Benin": "bj",
  "Bolivia": "bo",
  "Bosnia and Herzegovina": "ba",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Cameroon": "cm",
  "Canada": "ca",
  "Cape Verde": "cv",
  "Chile": "cl",
  "China": "cn",
  "Colombia": "co",
  "Congo": "cg",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Denmark": "dk",
  "Dominican Republic": "do",
  "DR Congo": "cd",
  "Ecuador": "ec",
  "Egypt": "eg",
  "England": "gb-eng",
  "Equatorial Guinea": "gq",
  "Finland": "fi",
  "France": "fr",
  "Gabon": "ga",
  "Gambia": "gm",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Greece": "gr",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Honduras": "hn",
  "Hungary": "hu",
  "Iceland": "is",
  "Iran": "ir",
  "Iraq": "iq",
  "Ireland": "ie",
  "Israel": "il",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jordan": "jo",
  "Kosovo": "xk",
  "Lebanon": "lb",
  "Mali": "ml",
  "Mexico": "mx",
  "Montenegro": "me",
  "Morocco": "ma",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Nigeria": "ng",
  "North Macedonia": "mk",
  "Northern Ireland": "gb-nir",
  "Norway": "no",
  "Panama": "pa",
  "Paraguay": "py",
  "Peru": "pe",
  "Poland": "pl",
  "Portugal": "pt",
  "Qatar": "qa",
  "Romania": "ro",
  "Russia": "ru",
  "Saudi Arabia": "sa",
  "Scotland": "gb-sct",
  "Senegal": "sn",
  "Serbia": "rs",
  "Slovakia": "sk",
  "Slovenia": "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Spain": "es",
  "Sweden": "se",
  "Switzerland": "ch",
  "Thailand": "th",
  "Togo": "tg",
  "Tunisia": "tn",
  "Turkey": "tr",
  "Ukraine": "ua",
  "Uruguay": "uy",
  "USA": "us",
  "Uzbekistan": "uz",
  "Venezuela": "ve",
  "Wales": "gb-wls",
  "Zambia": "zm",
  "Zimbabwe": "zw",
};

// Export an array of the names for the dropdown
export const topNationalities = Object.keys(nationalityToIsoCode).sort();

export function getFlagEmoji(nationality: string): string {
  return "🏳️"; // We now use FlagCDN, so we just return a fallback emoji for the db
}

export function getCountryCode(nationality: string): string | null {
  return nationalityToIsoCode[nationality] || null;
}
